library(G1DBN)
p <- 10
n <- 20
geneProp <- 0.05
MyNet <- SimulNetworkAdjMatrix(p,geneProp,c(-1.5,-0.5,0.5,1.5))
cat("\n==========================================\n")
cat("SIMULATION\n")
cat("Time series experiments with")
B <- runif(p,-1,1)
sigmaEps <- runif(p,0.1,0.5)
X0 <- B + rnorm(p,0,sigmaEps*10)
Xn <- SimulGeneExpressionAR1(MyNet$A,B,X0,sigmaEps,n)
cat("\n==========================================\n")
cat("NETWORK INFERENCE\n")
cat("Using a Dynamic Bayesian Network model\n")
cat("STEP 1...\n")
S1 <- DBNScoreStep1(Xn, method= 'ls')
cat("STEP 2...\n")
alpha1=0.5
S2 <- DBNScoreStep2(S1$S1ls, data=Xn, method= 'ls', alpha1=alpha1)
Step1InferredNet <- BuildNetwork(G1,1:p)
Step1InferredNet
alpha2=0.05
G2 <- BuildEdges(S2,threshold=alpha2,dec=FALSE)
Step2InferredNet <- BuildNetwork(G2,1:p)
cat("\n==========================================\n")
cat("SUMMARY\n")
cat("Plotting the results...\n")
split.screen(c(1,3))
G0 <- BuildEdges(MyNet$AdjMatrix,threshold=0.9,dec=TRUE)
all_parents=c(G0[,1],G1[,1], G2[,1])
all_targets=c(G0[,2],G1[,2], G2[,2])
posEdgesG0=1:dim(G0)[1]
posEdgesG1=(dim(G0)[1]+1):(dim(G0)[1]+dim(G1)[1])
posEdgesG2=(dim(G0)[1]+dim(G1)[1]+1):length(all_parents)
netAll = graph.edgelist(cbind(as.character(all_parents),as.character(all_targets)))
nodeCoord=layout.fruchterman.reingold(netAll)
screen(1)
netG1 = graph.edgelist(cbind(as.character(G1[,1]),as.character(G1[,2])))
G1toPlot=delete.edges(netAll, E(netAll)[c(posEdgesG0,posEdgesG2)-1] )
plot(G1toPlot, layout=nodeCoord, vertex.label = get.vertex.attribute(G1toPlot, name="name"), edge.arrow.size = 0.2, main="G1DBN Inferred network:\n Step 1")
screen(2)
netG2 = graph.edgelist(cbind(as.character(G2[,1]),as.character(G2[,2])))
G2toPlot=delete.edges(netAll, E(netAll)[c(posEdgesG0,posEdgesG1)-1 ] )
plot(G2toPlot, layout=nodeCoord, vertex.label = get.vertex.attribute(G2toPlot, name="name"),edge.arrow.size = 0.2, main="G1DBN Inferred network:\n Step 2")
screen(3)
net0 = graph.edgelist(cbind(as.character(G0[,1]),as.character(G0[,2])))
G0toPlot=delete.edges(netAll, E(netAll)[c(posEdgesG1,posEdgesG2)-1] )
plot(G0toPlot, layout=nodeCoord, vertex.label = get.vertex.attribute(G0toPlot, name="name"), edge.arrow.size = 0.2, main="Simulated network:")
close.screen(all = TRUE)
